# Generated by Django 5.2.4 on 2025-07-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='detection',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='detection',
            name='ward_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detection',
            name='detected_at',
            field=models.DateTimeField(),
        ),
    ]
