# Generated by Django 5.2.4 on 2025-07-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0002_detection_latitude_detection_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cleaned', 'Cleaned')], default='pending', max_length=10),
        ),
    ]
