# Generated by Django 5.2.4 on 2025-07-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0003_detection_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='image',
        ),
        migrations.AddField(
            model_name='detection',
            name='image_base64',
            field=models.TextField(blank=True),
        ),
    ]
